<?php
/*
 * Cart page uses the basket class
 */
require "Classes/basketClass.php";

$basket = new basket(); // Create a new basket object

// Look for form variables to determine if the cart first needs to be modified
if (
        isset($_POST["productid"]) and
        isset($_POST["price"]) and
        isset($_POST["name"]) and
        isset($_POST["quantity"])
) {
    // if update button and quantity = 0, or delete button, then we try to delete item
    if (($_POST["update"] && $_POST["quantity"] == 0) || $_POST["delete"]) {
      $basket->deleteItem($_POST["productid"], $_POST["name"]);
    }
    // else if quantity > 0 then we try to register or edit item
    else if ($_POST["quantity"] > 0) {
        if ($_POST["action"] == "replace") { // update from the cart
            $basket->registerItem($_POST["productid"], $_POST["name"], $_POST["quantity"], $_POST["price"]);
        }
        else {// from a product page add to existing quantity
            $oldqty = $basket->getItemQty($_POST["productid"]);
            $newqty = $oldqty + $_POST["quantity"];
            $basket->registerItem($_POST["productid"], $_POST["name"], $newqty, $_POST["price"]);
        }
    }
}

?>
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Cart</title>
    <link type="text/css" rel="stylesheet" href="Styles/nav.css">
    <link type="text/css" rel="stylesheet" href="Styles/cart.css">
  </head>
  <body>
  <div id="nav">
    <img src="Images/strawhut.jpg" id="navimage"/>
    <span id="navtitle">The Snack Shack</span>
    <span class="navlink" onclick="location.href='index.html'">Home</span>
    <span class="navlink" onclick="location.href='pages.html'">Product Pages</span>
    <span class="navlink" onclick="location.href='cart.php'">Cart</span>
  </div>
<?php
  // Display the HTML generated by the basket object
  $basket->toFormHTML();
?>
  </body>
</html>
